baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Muhammad Habibullah'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Halo!'
homeIntroContent = """
I am an Indonesian Software Engineer with a speciality in backend engineering.
I would love to talk about software architecture and system design.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/muhammadhabibullah/"

[[params.social]]
name = "github"
url = "https://github.com/muhammadhabibullah"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

#[[params.menu]]
#name = "about"
#url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[caches]
[caches.images]
dir = ':cacheDir/images'

[params.carouselHomepage]
enable = false  # default is true
